### ISSUE TITLE
raw_data_preprocess.py报错

### ISSUE THREAD

**Issue by wmathor** [jd-aig/nlp_baai#15]
```
File "raw_data_preprocess.py", line 279, in <module>
    train_items, dev_items = do_preprocess(args.directory, args.sess_turns)
File "raw_data_preprocess.py", line 81, in do_preprocess
    waiter = word[4]
```
难道我们用的不是同一个训练文件吗？我用的是data_train.txt，这个文件里面`商品编号`这一列有部分是空的

**Comment by nanzhao** [comment]
确实部分商品编码是空的，因为原始数据里面并非所有对话session都存在该数据，该字段并非mandatory字段。该字段并不会引起错误，我运行该文件时并不会报错，不知您那边遇到何种错误。如果需要帮助，您可以详细描述你的问题。

**Comment by wmathor** [comment]
> 确实部分商品编码是空的，因为原始数据里面并非所有对话session都存在该数据，该字段并非mandatory字段。该字段并不会引起错误，我运行该文件时并不会报错，不知您那边遇到何种错误。如果需要帮助，您可以详细描述你的问题。

感谢您的回复，不过我应该已经弃赛了，不好意思打扰了^^
